export const RECRUITMENT_STATUS = {
  PENDING_DECISION: 'pending_decision',
  PENDING_ARRIVAL: 'pending_arrival',
  NO_SHOW: 'no_show',
  TRIALING: 'trialing',
  REGULARIZED: 'regularized',
  REJECTED: 'rejected',
} as const;

export type RecruitmentStatus =
  (typeof RECRUITMENT_STATUS)[keyof typeof RECRUITMENT_STATUS];

export const RECRUITMENT_STATUS_VALUES = [
  RECRUITMENT_STATUS.PENDING_DECISION,
  RECRUITMENT_STATUS.PENDING_ARRIVAL,
  RECRUITMENT_STATUS.NO_SHOW,
  RECRUITMENT_STATUS.TRIALING,
  RECRUITMENT_STATUS.REGULARIZED,
  RECRUITMENT_STATUS.REJECTED,
] as const;

export const RECRUITMENT_STATUS_LABELS: Record<RecruitmentStatus, string> = {
  [RECRUITMENT_STATUS.PENDING_DECISION]: '待定',
  [RECRUITMENT_STATUS.PENDING_ARRIVAL]: '可试岗待到岗',
  [RECRUITMENT_STATUS.NO_SHOW]: '未到岗',
  [RECRUITMENT_STATUS.TRIALING]: '试岗中',
  [RECRUITMENT_STATUS.REGULARIZED]: '已转正',
  [RECRUITMENT_STATUS.REJECTED]: '已拒绝',
};

export const RECRUITMENT_STATUS_BADGE_CLASS_NAMES: Record<
  RecruitmentStatus,
  string
> = {
  [RECRUITMENT_STATUS.PENDING_DECISION]: 'bg-slate-100 text-slate-800',
  [RECRUITMENT_STATUS.PENDING_ARRIVAL]: 'bg-blue-100 text-blue-800',
  [RECRUITMENT_STATUS.NO_SHOW]: 'bg-gray-100 text-gray-800',
  [RECRUITMENT_STATUS.TRIALING]: 'bg-yellow-100 text-yellow-800',
  [RECRUITMENT_STATUS.REGULARIZED]: 'bg-green-100 text-green-800',
  [RECRUITMENT_STATUS.REJECTED]: 'bg-red-100 text-red-800',
};

export const ARRIVAL_DATE_OPTIONAL_RECRUITMENT_STATUSES = [
  RECRUITMENT_STATUS.PENDING_DECISION,
  RECRUITMENT_STATUS.NO_SHOW,
  RECRUITMENT_STATUS.REJECTED,
] as const satisfies readonly RecruitmentStatus[];
